name: 'Theme compile'

on:
  workflow_dispatch:

jobs:
  build:
    name: Install dependencies
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.ACTION_TOKEN }}

    # Checkout and merge branch master on deploy
    - name: Checkout/Merge git branches
      run: |
        git config --global user.email "internetdsa@gmail.com"
        git config --global user.name "GH - Actions"
        git fetch
        git checkout origin/deploy
        git merge master deploy
        
    # # Install NodeJS and compile files
    # - name: Install Node 
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14.x'

    # - name: Compile files
    #   run: |
    #     npm install -g yarn
    #     yarn
    #     yarn build:production
    #     rm -rf node_modules

    # # Install PHP Composer and dependencies
    # - name: Install PHP Composer
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '8.0'
    #     tools: composer:v2

    # - name: Execute composer
    #   run: |
    #     apt-get update
    #     ldconfig
    #     apt --fix-broken install -y
    #     composer install

    # Git commit/push to deploy branch
    - name: Commit/Push to deploy branch
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.ACTION_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout deploy
        git add .
        git commit -am "Compile theme versoin: $(git describe --abbrev=0)"
        git push